// Auto-generated by ampel-i18n-builder
// Do not edit manually

export type SupportedLanguage =
  | 'ar'
  | 'cs'
  | 'da'
  | 'de'
  | 'en'
  | 'en-GB'
  | 'es-ES'
  | 'es-MX'
  | 'fi'
  | 'fr'
  | 'he'
  | 'hi'
  | 'it'
  | 'ja'
  | 'ko'
  | 'nl'
  | 'no'
  | 'pl'
  | 'pt-BR'
  | 'ru'
  | 'sr'
  | 'sv'
  | 'th'
  | 'tr'
  | 'vi'
  | 'zh-CN'
  | 'zh-TW';

export const defaultLanguage: SupportedLanguage = 'en';

export const supportedLanguages: SupportedLanguage[] = [
  'ar',
  'cs',
  'da',
  'de',
  'en',
  'en-GB',
  'es-ES',
  'es-MX',
  'fi',
  'fr',
  'he',
  'hi',
  'it',
  'ja',
  'ko',
  'nl',
  'no',
  'pl',
  'pt-BR',
  'ru',
  'sr',
  'sv',
  'th',
  'tr',
  'vi',
  'zh-CN',
  'zh-TW',
];

export type TranslationNamespace =
  | 'analytics'
  | 'common'
  | 'dashboard'
  | 'errors'
  | 'merge'
  | 'repositories'
  | 'settings'
  | 'validation';

export interface AnalyticsTranslations {
  empty: {
    description: string;
    title: string;
  };
  health: {
    mergeTime: string;
    perWeek: string;
    reviewTime: string;
    stalePrs: string;
    throughput: string;
    title: string;
  };
  loading: {
    placeholder: string;
  };
  summary: {
    avgMergeTime: string;
    avgReviewTime: string;
    botPrs: string;
    prsMerged: string;
  };
  title: string;
}

export interface CommonTranslations {
  actions: {
    add: string;
    apply: string;
    cancel: string;
    clear: string;
    delete: string;
    edit: string;
    hideEmail: string;
    refresh: string;
    refreshing: string;
    remove: string;
    reset: string;
    save: string;
    saving: string;
    showEmail: string;
    viewOnProvider: string;
  };
  app: {
    add: string;
    apply: string;
    back: string;
    cancel: string;
    clear: string;
    close: string;
    delete: string;
    description: string;
    edit: string;
    error: string;
    filter: string;
    info: string;
    loading: string;
    name: string;
    next: string;
    previous: string;
    remove: string;
    reset: string;
    retry: string;
    save: string;
    search: string;
    success: string;
    title: string;
    warning: string;
  };
  auth: {
    alreadyHaveAccount: string;
    confirmPassword: string;
    createAccount: string;
    creatingAccount: string;
    displayName: string;
    displayNamePlaceholder: string;
    dontHaveAccount: string;
    email: string;
    emailPlaceholder: string;
    forgotPassword: string;
    getStarted: string;
    login: string;
    loginSuccess: string;
    logout: string;
    logoutSuccess: string;
    password: string;
    resetPassword: string;
    signIn: string;
    signInToContinue: string;
    signUp: string;
    signingIn: string;
    username: string;
    welcome: string;
    welcomeToAmpel: string;
  };
  language: {
    current: string;
    select: string;
  };
  navigation: {
    analytics: string;
    dashboard: string;
    documentation: string;
    help: string;
    merge: string;
    organizations: string;
    profile: string;
    pullRequests: string;
    repositories: string;
    settings: string;
  };
  pluralization: {
    comments_one: string;
    comments_other: string;
    pullRequests_one: string;
    pullRequests_other: string;
    requests_one: string;
    requests_other: string;
  };
  status: {
    trafficLight: string;
  };
  theme: {
    auto: string;
    dark: string;
    light: string;
    toggle: string;
  };
  time: {
    daysAgo: string;
    daysAgo_other: string;
    hoursAgo: string;
    hoursAgo_other: string;
    minutesAgo: string;
    minutesAgo_other: string;
    monthsAgo: string;
    monthsAgo_other: string;
    now: string;
    weeksAgo: string;
    weeksAgo_other: string;
  };
  visibility: {
    archived: string;
    private: string;
    public: string;
  };
}

export interface DashboardTranslations {
  actions: {
    approve: string;
    comment: string;
    deselectAll: string;
    merge: string;
    refresh: string;
    requestChanges: string;
    selectAll: string;
    viewOnProvider: string;
  };
  blockers: {
    awaitingReview: string;
    changesRequested: string;
    ciFailed: string;
    ciPending: string;
    conflicts: string;
    draft: string;
    needsReview: string;
  };
  empty: {
    action: string;
    description: string;
    title: string;
  };
  filters: {
    all: string;
    assignee: string;
    author: string;
    closed: string;
    draft: string;
    label: string;
    merged: string;
    onlyWithPrs: string;
    open: string;
    provider: string;
    repository: string;
  };
  pr: {
    additions: string;
    author: string;
    comments: string;
    createdAt: string;
    deletions: string;
    number: string;
    sourceBranch: string;
    targetBranch: string;
    updatedAt: string;
  };
  prDashboard: string;
  sort: {
    author: string;
    created: string;
    repository: string;
    status: string;
    title: string;
    updated: string;
  };
  stats: {
    blocked: string;
    inProgress: string;
    needsAttention: string;
    open: string;
    openPRs: string;
    ready: string;
    readyToMerge: string;
    total: string;
    totalRepositories: string;
  };
  status: {
    closed: string;
    draft: string;
    green: string;
    merged: string;
    red: string;
    yellow: string;
  };
  subtitle: string;
  title: string;
  views: {
    grid: string;
    list: string;
    prs: string;
    pullRequests: string;
    repositoryGrid: string;
    repositoryList: string;
    table: string;
  };
}

export interface ErrorsTranslations {
  auth: {
    failedToCreateAccount: string;
    forbidden: string;
    invalidCredentials: string;
    invalidEmailOrPassword: string;
    loginFailed: string;
    registrationFailed: string;
    sessionExpired: string;
    tokenExpired: string;
    unauthorized: string;
  };
  general: {
    unknownError: string;
  };
  generic: {
    goHome: string;
    message: string;
    retry: string;
    somethingWentWrong: string;
    title: string;
  };
  network: {
    message: string;
    offline: string;
    title: string;
  };
  notFound: {
    goHome: string;
    message: string;
    title: string;
  };
  pr: {
    approveFailed: string;
    commentFailed: string;
    loadFailed: string;
    mergeFailed: string;
  };
  provider: {
    connectionFailed: string;
    invalidToken: string;
    notFound: string;
    rateLimited: string;
  };
  repository: {
    accessDenied: string;
    loadFailed: string;
    notFound: string;
  };
  validation: {
    invalidEmail: string;
    invalidUrl: string;
    maxLength: string;
    minLength: string;
    passwordMismatch: string;
    required: string;
  };
}

export interface MergeTranslations {
  actions: {
    merge: string;
    merging: string;
  };
  blockers: {
    awaitingReview: string;
    changesRequested: string;
    ciFailed: string;
    ciPending: string;
    conflicts: string;
    draft: string;
    needsReview: string;
  };
  emptyState: {
    noPrsReady: string;
    requirements: {
      ciPassing: string;
      noConflicts: string;
      requiredApprovals: string;
    };
  };
  options: {
    deleteBranch: string;
    description: string;
    strategies: {
      merge: string;
      rebase: string;
      squash: string;
    };
    strategy: string;
    title: string;
  };
  repository: {
    prCount: string;
    prCount_other: string;
  };
  results: {
    allSuccess: string;
    close: string;
    stats: {
      failed: string;
      merged: string;
      skipped: string;
      total: string;
    };
    status: {
      failed: string;
      skipped: string;
      success: string;
    };
    summary: string;
    title: string;
  };
  sections: {
    notReadyDescription: string;
    notReadyTitle: string;
    readyDescription: string;
    readyTitle: string;
  };
  selection: {
    count: string;
    deselectAll: string;
    selectAll: string;
  };
  subtitle: string;
  title: string;
  toast: {
    mergeFailed: string;
    mergeSuccess: string;
    mergeSuccessDescription: string;
    someMergesFailed: string;
    someMergesFailedDescription: string;
  };
}

export interface RepositoriesTranslations {
  addFrom: {
    addAll: string;
    close: string;
    empty: string;
    title: string;
  };
  empty: {
    description: string;
    title: string;
  };
  providers: {
    connected: string;
    title: string;
  };
  search: {
    placeholder: string;
  };
  table: {
    actions: string;
    provider: string;
    prs: string;
    repository: string;
    status: string;
  };
  title: string;
  toast: {
    addFailed: string;
    added: string;
    addedDescription: string;
    bulkAddFailed: string;
    bulkAddFailedDescription: string;
    bulkAdded: string;
    bulkAddedDescription: string;
    bulkAddedFailed: string;
    removeFailed: string;
    removed: string;
    removedDescription: string;
  };
}

export interface SettingsTranslations {
  account: {
    avatar: string;
    changePassword: string;
    deleteAccount: string;
    deleteAccountWarning: string;
    displayName: string;
    displayNamePlaceholder: string;
    email: string;
    emailAddress: string;
    emailPlaceholder: string;
    memberSince: string;
    notSet: string;
    profile: string;
    unknown: string;
    yourAccountInfo: string;
  };
  behavior: {
    autoRefresh: string;
    autoRefreshDescription: string;
    defaultView: string;
    defaultViewDescription: string;
    prPerPage: string;
    prPerPageDescription: string;
    refreshInterval: string;
    refreshIntervalDescription: string;
    title: string;
  };
  filtersReset: string;
  filtersResetSuccess: string;
  filtersUpdateFailed: string;
  filtersUpdateSuccess: string;
  filtersUpdated: string;
  general: {
    language: string;
    languageDescription: string;
    theme: string;
    themeDescription: string;
    timezone: string;
    timezoneDescription: string;
  };
  language: {
    description: string;
    title: string;
  };
  notifications: {
    email: string;
    emailDescription: string;
    mentions: string;
    mentionsDescription: string;
    prUpdates: string;
    prUpdatesDescription: string;
    reviews: string;
    reviewsDescription: string;
    title: string;
  };
  prFilters: {
    allowedActors: string;
    allowedActorsDescription: string;
    allowedActorsPlaceholder: string;
    description: string;
    maxAgeDays: string;
    maxAgeDaysDescription: string;
    maxAgeDaysPlaceholder: string;
    skipLabels: string;
    skipLabelsDescription: string;
    skipLabelsPlaceholder: string;
    title: string;
  };
  profileUpdateFailed: string;
  profileUpdateSuccess: string;
  profileUpdated: string;
  providers: {
    bitbucket: string;
    connect: string;
    connected: string;
    disconnect: string;
    github: string;
    gitlab: string;
    notConnected: string;
    token: string;
    tokenDescription: string;
    tokenInstructions: string;
    tokenPlaceholder: string;
  };
  repositories: {
    filter: string;
    filterDescription: string;
    showArchived: string;
    showArchivedDescription: string;
    showForks: string;
    showForksDescription: string;
  };
  reset: string;
  resetConfirm: string;
  save: string;
  saved: string;
  subtitle: string;
  tabs: {
    account: string;
    accounts: string;
    appearance: string;
    behavior: string;
    filters: string;
    general: string;
    notifications: string;
    prFilters: string;
    profile: string;
    providers: string;
    repositories: string;
    repositoryFilters: string;
  };
  title: string;
  updateFailed: string;
}

export interface ValidationTranslations {
  alphanum: string;
  date: string;
  dateRange: string;
  email: string;
  fields: {
    confirmPassword: string;
    displayName: string;
    email: string;
    password: string;
  };
  fileSize: string;
  fileType: string;
  integer: string;
  invalidEmail: string;
  max: string;
  maxLength: string;
  messages: {
    displayNameRequired: string;
    emailRequired: string;
    passwordMinLength: string;
    passwordRequired: string;
  };
  min: string;
  minLength: string;
  negative: string;
  numeric: string;
  passwordMismatch: string;
  passwordsDontMatch: string;
  pattern: string;
  positive: string;
  required: string;
  unique: string;
  url: string;
}

export interface Translations {
  analytics: AnalyticsTranslations;
  common: CommonTranslations;
  dashboard: DashboardTranslations;
  errors: ErrorsTranslations;
  merge: MergeTranslations;
  repositories: RepositoriesTranslations;
  settings: SettingsTranslations;
  validation: ValidationTranslations;
}
