#!/bin/bash
# Install git hooks for i18n validation
# Usage: ./scripts/install-git-hooks.sh

set -e

HOOKS_DIR=".git/hooks"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "🔧 Installing git hooks for i18n validation..."

# Check if .git directory exists
if [ ! -d "$PROJECT_ROOT/.git" ]; then
  echo "❌ Error: Not a git repository. Please run from project root."
  exit 1
fi

# Create hooks directory if it doesn't exist
mkdir -p "$PROJECT_ROOT/$HOOKS_DIR"

# Install pre-commit hook
echo "📝 Installing pre-commit hook..."
cat > "$PROJECT_ROOT/$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
# Pre-commit hook for i18n validation
# Auto-generated by scripts/install-git-hooks.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}🌐 Running i18n validation...${NC}"

# Track overall status
VALIDATION_FAILED=0

# Get list of changed files
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

# Check if any translation files were changed
BACKEND_I18N_CHANGED=$(echo "$CHANGED_FILES" | grep -E '^crates/ampel-api/locales/.*\.(yml|yaml)$' || true)
FRONTEND_I18N_CHANGED=$(echo "$CHANGED_FILES" | grep -E '^frontend/public/locales/.*\.json$' || true)
I18N_BUILDER_CHANGED=$(echo "$CHANGED_FILES" | grep -E '^crates/ampel-i18n-builder/' || true)

# Skip validation if no i18n files changed
if [ -z "$BACKEND_I18N_CHANGED" ] && [ -z "$FRONTEND_I18N_CHANGED" ] && [ -z "$I18N_BUILDER_CHANGED" ]; then
  echo -e "${GREEN}✅ No translation files changed, skipping validation${NC}"
  exit 0
fi

# Validate backend translations if changed
if [ -n "$BACKEND_I18N_CHANGED" ] || [ -n "$I18N_BUILDER_CHANGED" ]; then
  echo -e "${YELLOW}Validating backend translations...${NC}"

  # Check if ampel-i18n-builder exists
  if ! cargo build --package ampel-i18n-builder --quiet 2>/dev/null; then
    echo -e "${YELLOW}⚠️  ampel-i18n-builder not available, skipping backend validation${NC}"
  else
    # Run coverage check with timeout
    if timeout 5s cargo run --package ampel-i18n-builder --quiet -- check --min-coverage 95 2>&1; then
      echo -e "${GREEN}✅ Backend translations validated${NC}"
    else
      echo -e "${RED}❌ Backend translation validation failed${NC}"
      VALIDATION_FAILED=1
    fi
  fi
fi

# Validate frontend translations if changed
if [ -n "$FRONTEND_I18N_CHANGED" ]; then
  echo -e "${YELLOW}Validating frontend translations...${NC}"

  cd frontend

  # Check if dependencies are installed
  if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}⚠️  Frontend dependencies not installed, skipping validation${NC}"
    cd ..
  else
    # Validate JSON syntax
    JSON_VALID=true
    for file in public/locales/**/*.json; do
      if [ -f "$file" ]; then
        if ! node -e "JSON.parse(require('fs').readFileSync('$file', 'utf8'))" 2>/dev/null; then
          echo -e "${RED}❌ Invalid JSON in: $file${NC}"
          JSON_VALID=false
          VALIDATION_FAILED=1
        fi
      fi
    done

    if [ "$JSON_VALID" = true ]; then
      echo -e "${GREEN}✅ All JSON files valid${NC}"
    fi

    # Run coverage check if script exists
    if [ -f "scripts/i18n-coverage-report.js" ]; then
      if timeout 5s node scripts/i18n-coverage-report.js --check --min-coverage 95 2>&1; then
        echo -e "${GREEN}✅ Frontend translation coverage passed${NC}"
      else
        echo -e "${RED}❌ Frontend translation coverage below threshold${NC}"
        VALIDATION_FAILED=1
      fi
    fi

    cd ..
  fi
fi

# Final status
if [ $VALIDATION_FAILED -eq 1 ]; then
  echo -e "${RED}❌ i18n validation failed${NC}"
  echo -e "${YELLOW}💡 Fix the issues above or use 'git commit --no-verify' to skip validation${NC}"
  exit 1
else
  echo -e "${GREEN}✅ i18n validation passed${NC}"
  exit 0
fi
EOF

# Make hook executable
chmod +x "$PROJECT_ROOT/$HOOKS_DIR/pre-commit"

echo -e "${GREEN}✅ Pre-commit hook installed${NC}"

# Install commit-msg hook for translation commit message validation
echo "📝 Installing commit-msg hook..."
cat > "$PROJECT_ROOT/$HOOKS_DIR/commit-msg" << 'EOF'
#!/bin/bash
# Commit message hook for i18n commits
# Auto-generated by scripts/install-git-hooks.sh

set -e

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check if this is an i18n commit
if echo "$COMMIT_MSG" | grep -qE '^(feat|fix|chore|docs)\(i18n\):'; then
  # Get list of changed files
  CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

  # Ensure i18n commits only modify i18n files
  NON_I18N_FILES=$(echo "$CHANGED_FILES" | grep -vE '(locales/|i18n|IMPLEMENTATION_ROADMAP)' || true)

  if [ -n "$NON_I18N_FILES" ]; then
    echo "❌ Error: i18n commit contains non-i18n files:"
    echo "$NON_I18N_FILES"
    echo ""
    echo "Please separate i18n changes from other changes."
    exit 1
  fi
fi

exit 0
EOF

chmod +x "$PROJECT_ROOT/$HOOKS_DIR/commit-msg"

echo -e "${GREEN}✅ Commit-msg hook installed${NC}"
echo ""
echo "🎉 Git hooks successfully installed!"
echo ""
echo "Installed hooks:"
echo "  - pre-commit: Validates translation files before commit"
echo "  - commit-msg: Enforces i18n commit message conventions"
echo ""
echo "To bypass hooks: git commit --no-verify"
