use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // remediation_policy ---------------------------------------------------
        manager
            .create_table(
                Table::create()
                    .table(RemediationPolicy::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RemediationPolicy::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::ScopeType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RemediationPolicy::ScopeId).uuid().not_null())
                    .col(
                        ColumnDef::new(RemediationPolicy::Enabled)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::MinOpenPrs)
                            .integer()
                            .not_null()
                            .default(2),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::PrSelection)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::AutonomyLevel)
                            .string()
                            .not_null()
                            .default("dry_run_only"),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::RemediationTier)
                            .string()
                            .not_null()
                            .default("consolidate_only"),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::MaxPrsPerRun)
                            .integer()
                            .not_null()
                            .default(5),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::AllowedTargets)
                            .text()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::SkipDraft)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::RequireGreenBeforeMerge)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::AirGapped)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::AutoMergeEnabled)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(RemediationPolicy::AutoMergeRule).text())
                    .col(
                        ColumnDef::new(RemediationPolicy::RequireHumanApproval)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(ColumnDef::new(RemediationPolicy::AgentBudget).text())
                    .col(ColumnDef::new(RemediationPolicy::NotificationConfig).text())
                    .col(ColumnDef::new(RemediationPolicy::PlaybookRef).text())
                    .col(
                        ColumnDef::new(RemediationPolicy::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(RemediationPolicy::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // Unique policy per scope
        manager
            .create_index(
                Index::create()
                    .name("idx_remediation_policy_unique_scope")
                    .table(RemediationPolicy::Table)
                    .col(RemediationPolicy::ScopeType)
                    .col(RemediationPolicy::ScopeId)
                    .unique()
                    .to_owned(),
            )
            .await?;

        // remediation_run ------------------------------------------------------
        manager
            .create_table(
                Table::create()
                    .table(RemediationRun::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RemediationRun::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RemediationRun::RepositoryId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RemediationRun::PolicyId).uuid().not_null())
                    .col(
                        ColumnDef::new(RemediationRun::TriggeredBy)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RemediationRun::TriggeredByUserId).uuid())
                    .col(ColumnDef::new(RemediationRun::State).string().not_null())
                    .col(
                        ColumnDef::new(RemediationRun::PrSelectionSnapshot)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RemediationRun::ConsolidationPlan).text())
                    .col(ColumnDef::new(RemediationRun::ConsolidatedPrNumber).big_integer())
                    .col(
                        ColumnDef::new(RemediationRun::Merged)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(RemediationRun::BranchName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RemediationRun::CiStatus)
                            .string()
                            .not_null()
                            .default("pending"),
                    )
                    .col(ColumnDef::new(RemediationRun::CiLogsUrl).string())
                    .col(ColumnDef::new(RemediationRun::MergeStrategy).string())
                    .col(
                        ColumnDef::new(RemediationRun::Attempts)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(RemediationRun::ErrorMessage).text())
                    .col(ColumnDef::new(RemediationRun::ErrorClass).string())
                    .col(
                        ColumnDef::new(RemediationRun::StartedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RemediationRun::CompletedAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(RemediationRun::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(RemediationRun::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_remediation_run_repository_id")
                    .table(RemediationRun::Table)
                    .col(RemediationRun::RepositoryId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_remediation_run_state")
                    .table(RemediationRun::Table)
                    .col(RemediationRun::State)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_remediation_run_policy_id")
                    .table(RemediationRun::Table)
                    .col(RemediationRun::PolicyId)
                    .to_owned(),
            )
            .await?;

        // remediation_run_pr ---------------------------------------------------
        manager
            .create_table(
                Table::create()
                    .table(RemediationRunPr::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RemediationRunPr::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RemediationRunPr::RemediationRunId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RemediationRunPr::PrNumber)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RemediationRunPr::Disposition)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RemediationRunPr::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_remediation_run_pr_run")
                            .from(RemediationRunPr::Table, RemediationRunPr::RemediationRunId)
                            .to(RemediationRun::Table, RemediationRun::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_remediation_run_pr_run_id")
                    .table(RemediationRunPr::Table)
                    .col(RemediationRunPr::RemediationRunId)
                    .to_owned(),
            )
            .await?;

        // remediation_agent_session -------------------------------------------
        manager
            .create_table(
                Table::create()
                    .table(RemediationAgentSession::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RemediationAgentSession::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(RemediationAgentSession::RemediationRunId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RemediationAgentSession::ModelProviderAccountId).uuid())
                    .col(ColumnDef::new(RemediationAgentSession::PlaybookRef).text())
                    .col(
                        ColumnDef::new(RemediationAgentSession::Iterations)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(RemediationAgentSession::MaxIterations).integer())
                    .col(
                        ColumnDef::new(RemediationAgentSession::TokensUsed)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(RemediationAgentSession::CostUsd).string())
                    .col(
                        ColumnDef::new(RemediationAgentSession::Status)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(RemediationAgentSession::TranscriptRef).string())
                    .col(
                        ColumnDef::new(RemediationAgentSession::StartedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RemediationAgentSession::CompletedAt)
                            .timestamp_with_time_zone(),
                    )
                    .col(
                        ColumnDef::new(RemediationAgentSession::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_remediation_agent_session_run")
                            .from(
                                RemediationAgentSession::Table,
                                RemediationAgentSession::RemediationRunId,
                            )
                            .to(RemediationRun::Table, RemediationRun::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_remediation_agent_session_run_id")
                    .table(RemediationAgentSession::Table)
                    .col(RemediationAgentSession::RemediationRunId)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Drop in reverse FK dependency order.
        manager
            .drop_table(
                Table::drop()
                    .table(RemediationAgentSession::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(RemediationRunPr::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(RemediationRun::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(RemediationPolicy::Table).to_owned())
            .await?;

        Ok(())
    }
}

#[derive(DeriveIden)]
enum RemediationPolicy {
    Table,
    Id,
    ScopeType,
    ScopeId,
    Enabled,
    MinOpenPrs,
    PrSelection,
    AutonomyLevel,
    RemediationTier,
    MaxPrsPerRun,
    AllowedTargets,
    SkipDraft,
    RequireGreenBeforeMerge,
    AirGapped,
    AutoMergeEnabled,
    AutoMergeRule,
    RequireHumanApproval,
    AgentBudget,
    NotificationConfig,
    PlaybookRef,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum RemediationRun {
    Table,
    Id,
    RepositoryId,
    PolicyId,
    TriggeredBy,
    TriggeredByUserId,
    State,
    PrSelectionSnapshot,
    ConsolidationPlan,
    ConsolidatedPrNumber,
    Merged,
    BranchName,
    CiStatus,
    CiLogsUrl,
    MergeStrategy,
    Attempts,
    ErrorMessage,
    ErrorClass,
    StartedAt,
    CompletedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum RemediationRunPr {
    Table,
    Id,
    RemediationRunId,
    PrNumber,
    Disposition,
    CreatedAt,
}

#[derive(DeriveIden)]
enum RemediationAgentSession {
    Table,
    Id,
    RemediationRunId,
    ModelProviderAccountId,
    PlaybookRef,
    Iterations,
    MaxIterations,
    TokensUsed,
    CostUsd,
    Status,
    TranscriptRef,
    StartedAt,
    CompletedAt,
    CreatedAt,
}
