// Auto-generated by ampel-i18n-builder
// Do not edit manually

export type SupportedLanguage =
  | 'ar'
  | 'cs'
  | 'da'
  | 'de'
  | 'en'
  | 'en-GB'
  | 'es-ES'
  | 'es-MX'
  | 'fi'
  | 'fr'
  | 'he'
  | 'hi'
  | 'it'
  | 'ja'
  | 'ko'
  | 'nl'
  | 'no'
  | 'pl'
  | 'pt-BR'
  | 'ru'
  | 'sr'
  | 'sv'
  | 'th'
  | 'tr'
  | 'vi'
  | 'zh-CN'
  | 'zh-TW';

export const defaultLanguage: SupportedLanguage = 'en';

export const supportedLanguages: SupportedLanguage[] = [
  'ar',
  'cs',
  'da',
  'de',
  'en',
  'en-GB',
  'es-ES',
  'es-MX',
  'fi',
  'fr',
  'he',
  'hi',
  'it',
  'ja',
  'ko',
  'nl',
  'no',
  'pl',
  'pt-BR',
  'ru',
  'sr',
  'sv',
  'th',
  'tr',
  'vi',
  'zh-CN',
  'zh-TW',
];

export type TranslationNamespace =
  | 'accounts'
  | 'analytics'
  | 'behavior'
  | 'common'
  | 'dashboard'
  | 'errors'
  | 'merge'
  | 'notifications'
  | 'providers'
  | 'remediation'
  | 'repositories'
  | 'settings'
  | 'validation';

export interface AccountsTranslations {
  add: {
    backToAccounts: string;
    form: {
      accountLabel: string;
      accountLabelDescription: string;
      accountLabelPlaceholder: string;
      accountLabelRequired: string;
      appPassword: string;
      bitbucketUsername: string;
      bitbucketUsernameDescription: string;
      bitbucketUsernamePlaceholder: string;
      hideToken: string;
      instanceUrl: string;
      instanceUrlDescription: string;
      instanceUrlPlaceholder: string;
      provider: string;
      selectProvider: string;
      showToken: string;
      token: string;
      tokenDescription: string;
      tokenPlaceholder: string;
      tokenPlaceholder_bitbucket: string;
      tokenPlaceholder_github: string;
      tokenPlaceholder_gitlab: string;
      tokenRequired: string;
      usernameRequired: string;
    };
    submit: string;
    submitting: string;
    subtitle: string;
    title: string;
  };
  addAccount: string;
  addFirstAccount: string;
  card: {
    actions: {
      delete: string;
      edit: string;
      setDefault: string;
      validate: string;
    };
    expires: string;
    neverExpires: string;
    repositories: string;
    status: {
      default: string;
      expired: string;
      invalid: string;
      pending: string;
      valid: string;
    };
    validated: string;
  };
  delete: {
    cancel: string;
    confirm: string;
    deleting: string;
    description: string;
    title: string;
  };
  description: string;
  edit: {
    accountInfo: string;
    backToAccounts: string;
    form: {
      accountLabel: string;
      accountLabelDescription: string;
      accountLabelPlaceholder: string;
      active: string;
      activeDescription: string;
      currentToken: string;
      hideToken: string;
      showToken: string;
      token: string;
      tokenDescription: string;
      tokenPlaceholder: string;
    };
    info: {
      email: string;
      instance: string;
      repositories: string;
      status: string;
      username: string;
    };
    notFound: string;
    submit: string;
    submitting: string;
    subtitle: string;
    title: string;
  };
  noAccountsYet: string;
  title: string;
  toast: {
    connected: string;
    connectedDescription: string;
    connectionFailed: string;
    defaultUpdateFailed: string;
    defaultUpdated: string;
    defaultUpdatedDescription: string;
    deleteFailed: string;
    deleted: string;
    deletedDescription: string;
    tokenInvalid: string;
    tokenInvalidDescription: string;
    tokenValid: string;
    tokenValidDescription: string;
    updateFailed: string;
    updated: string;
    updatedDescription: string;
    validationFailed: string;
  };
}

export interface AnalyticsTranslations {
  empty: {
    description: string;
    title: string;
  };
  health: {
    mergeTime: string;
    perWeek: string;
    reviewTime: string;
    stalePrs: string;
    throughput: string;
    title: string;
  };
  loading: {
    placeholder: string;
  };
  summary: {
    avgMergeTime: string;
    avgReviewTime: string;
    botPrs: string;
    prsMerged: string;
  };
  title: string;
}

export interface BehaviorTranslations {
  delay: {
    description: string;
    placeholder: string;
    title: string;
  };
  options: {
    allowNoReviews: string;
    allowNoReviewsDescription: string;
    deleteBranch: string;
    deleteBranchDescription: string;
    requireApproval: string;
    requireApprovalDescription: string;
  };
  strategy: {
    description: string;
    merge: string;
    mergeDescription: string;
    rebase: string;
    rebaseDescription: string;
    squash: string;
    squashDescription: string;
    title: string;
  };
  title: string;
  toast: {
    updateFailed: string;
    updated: string;
    updatedDescription: string;
  };
}

export interface CommonTranslations {
  actions: {
    add: string;
    apply: string;
    cancel: string;
    clear: string;
    delete: string;
    edit: string;
    hideEmail: string;
    refresh: string;
    refreshing: string;
    remove: string;
    reset: string;
    save: string;
    saving: string;
    showEmail: string;
    viewOnProvider: string;
  };
  app: {
    add: string;
    apply: string;
    back: string;
    cancel: string;
    clear: string;
    close: string;
    delete: string;
    description: string;
    edit: string;
    error: string;
    filter: string;
    info: string;
    loading: string;
    name: string;
    next: string;
    previous: string;
    remove: string;
    reset: string;
    retry: string;
    save: string;
    search: string;
    success: string;
    title: string;
    warning: string;
  };
  auth: {
    alreadyHaveAccount: string;
    confirmPassword: string;
    createAccount: string;
    creatingAccount: string;
    displayName: string;
    displayNamePlaceholder: string;
    dontHaveAccount: string;
    email: string;
    emailPlaceholder: string;
    forgotPassword: string;
    getStarted: string;
    login: string;
    loginSuccess: string;
    logout: string;
    logoutSuccess: string;
    password: string;
    resetPassword: string;
    signIn: string;
    signInToContinue: string;
    signUp: string;
    signingIn: string;
    username: string;
    welcome: string;
    welcomeToAmpel: string;
  };
  language: {
    current: string;
    select: string;
  };
  navigation: {
    analytics: string;
    dashboard: string;
    documentation: string;
    help: string;
    merge: string;
    organizations: string;
    profile: string;
    pullRequests: string;
    repositories: string;
    settings: string;
  };
  pluralization: {
    comments_one: string;
    comments_other: string;
    pullRequests_one: string;
    pullRequests_other: string;
    requests_one: string;
    requests_other: string;
  };
  status: {
    trafficLight: string;
  };
  theme: {
    auto: string;
    dark: string;
    light: string;
    toggle: string;
  };
  time: {
    daysAgo: string;
    daysAgo_other: string;
    hoursAgo: string;
    hoursAgo_other: string;
    minutesAgo: string;
    minutesAgo_other: string;
    monthsAgo: string;
    monthsAgo_other: string;
    now: string;
    weeksAgo: string;
    weeksAgo_other: string;
  };
  visibility: {
    archived: string;
    private: string;
    public: string;
  };
}

export interface DashboardTranslations {
  actions: {
    approve: string;
    comment: string;
    deselectAll: string;
    merge: string;
    refresh: string;
    requestChanges: string;
    selectAll: string;
    viewOnProvider: string;
  };
  blockers: {
    awaitingReview: string;
    changesRequested: string;
    ciFailed: string;
    ciPending: string;
    conflicts: string;
    draft: string;
    needsReview: string;
  };
  empty: {
    action: string;
    description: string;
    title: string;
  };
  filters: {
    all: string;
    assignee: string;
    author: string;
    closed: string;
    draft: string;
    label: string;
    merged: string;
    onlyWithPrs: string;
    open: string;
    prStatus: {
      all: string;
      blocked: string;
      pending: string;
      ready: string;
    };
    provider: string;
    repository: string;
  };
  pr: {
    additions: string;
    author: string;
    comments: string;
    createdAt: string;
    deletions: string;
    number: string;
    sourceBranch: string;
    targetBranch: string;
    updatedAt: string;
  };
  prDashboard: string;
  refresh: {
    complete: string;
    completed: string;
    currentRepository: string;
    description: string;
    progress: string;
    started: string;
    title: string;
  };
  sort: {
    author: string;
    created: string;
    repository: string;
    status: string;
    title: string;
    updated: string;
  };
  stats: {
    blocked: string;
    inProgress: string;
    needsAttention: string;
    open: string;
    openPRs: string;
    ready: string;
    readyToMerge: string;
    total: string;
    totalRepositories: string;
  };
  status: {
    closed: string;
    draft: string;
    green: string;
    merged: string;
    red: string;
    yellow: string;
  };
  subtitle: string;
  table: {
    columns: {
      lastUpdated: string;
      provider: string;
      prs: string;
      repository: string;
      status: string;
      visibility: string;
    };
  };
  title: string;
  views: {
    grid: string;
    list: string;
    prs: string;
    pullRequests: string;
    repositoryGrid: string;
    repositoryList: string;
    table: string;
  };
}

export interface ErrorsTranslations {
  auth: {
    failedToCreateAccount: string;
    forbidden: string;
    invalidCredentials: string;
    invalidEmailOrPassword: string;
    loginFailed: string;
    registrationFailed: string;
    sessionExpired: string;
    tokenExpired: string;
    unauthorized: string;
  };
  boundary: {
    description: string;
    details: string;
    reload: string;
    title: string;
    tryAgain: string;
  };
  general: {
    unknownError: string;
  };
  generic: {
    goHome: string;
    message: string;
    retry: string;
    somethingWentWrong: string;
    title: string;
  };
  network: {
    message: string;
    offline: string;
    title: string;
  };
  notFound: {
    goHome: string;
    message: string;
    title: string;
  };
  pr: {
    approveFailed: string;
    commentFailed: string;
    loadFailed: string;
    mergeFailed: string;
  };
  provider: {
    connectionFailed: string;
    invalidToken: string;
    notFound: string;
    rateLimited: string;
  };
  repository: {
    accessDenied: string;
    loadFailed: string;
    notFound: string;
  };
  validation: {
    invalidEmail: string;
    invalidUrl: string;
    maxLength: string;
    minLength: string;
    passwordMismatch: string;
    required: string;
  };
}

export interface MergeTranslations {
  actions: {
    merge: string;
    merging: string;
  };
  blockers: {
    awaitingReview: string;
    changesRequested: string;
    ciFailed: string;
    ciPending: string;
    conflicts: string;
    draft: string;
    needsReview: string;
  };
  dialog: {
    cancel: string;
    deleteBranch: string;
    merge: string;
    merging: string;
    strategy: {
      merge: string;
      mergeDescription: string;
      rebase: string;
      rebaseDescription: string;
      squash: string;
      squashDescription: string;
      title: string;
    };
    subtitle: string;
    title: string;
  };
  emptyState: {
    noPrsReady: string;
    requirements: {
      ciPassing: string;
      noConflicts: string;
      requiredApprovals: string;
    };
  };
  options: {
    deleteBranch: string;
    description: string;
    strategies: {
      merge: string;
      rebase: string;
      squash: string;
    };
    strategy: string;
    title: string;
  };
  repository: {
    prCount: string;
    prCount_other: string;
  };
  results: {
    allSuccess: string;
    close: string;
    stats: {
      failed: string;
      merged: string;
      skipped: string;
      total: string;
    };
    status: {
      failed: string;
      skipped: string;
      success: string;
    };
    summary: string;
    title: string;
  };
  sections: {
    notReadyDescription: string;
    notReadyTitle: string;
    readyDescription: string;
    readyTitle: string;
  };
  selection: {
    count: string;
    deselectAll: string;
    selectAll: string;
  };
  subtitle: string;
  title: string;
  toast: {
    failed: string;
    failedDescription: string;
    mergeFailed: string;
    mergeSuccess: string;
    mergeSuccessDescription: string;
    someMergesFailed: string;
    someMergesFailedDescription: string;
    success: string;
    successDescription: string;
  };
}

export interface NotificationsTranslations {
  email: {
    add: string;
    enable: string;
    enableDescription: string;
    fromAddress: string;
    fromAddressPlaceholder: string;
    smtpHost: string;
    smtpHostPlaceholder: string;
    smtpPassword: string;
    smtpPasswordPlaceholder: string;
    smtpPort: string;
    smtpPortPlaceholder: string;
    smtpUser: string;
    smtpUserPlaceholder: string;
    testFailed: string;
    testMessage: string;
    testSending: string;
    testSuccess: string;
    title: string;
    toAddresses: string;
    toAddressesDescription: string;
    toAddressesPlaceholder: string;
    useTls: string;
  };
  merge: {
    description: string;
    notifyOnConflict: string;
    notifyOnConflictDescription: string;
    notifyOnFailure: string;
    notifyOnFailureDescription: string;
    notifyOnSuccess: string;
    notifyOnSuccessDescription: string;
    title: string;
  };
  slack: {
    channel: string;
    channelDescription: string;
    channelPlaceholder: string;
    enable: string;
    enableDescription: string;
    testFailed: string;
    testMessage: string;
    testSending: string;
    testSuccess: string;
    title: string;
    webhookUrl: string;
    webhookUrlDescription: string;
    webhookUrlPlaceholder: string;
  };
  title: string;
  toast: {
    updateFailed: string;
    updated: string;
    updatedDescription: string;
  };
}

export interface ProvidersTranslations {
  bitbucket: {
    linkText: string;
    permissions: {
      accountRead: string;
      pullRequestsRead: string;
      pullRequestsWrite: string;
      repositoriesRead: string;
      repositoriesWrite: string;
    };
    steps: {
      step1: string;
      step2: string;
      step3: string;
      step4: string;
      step5: string;
      step6: string;
    };
    title: string;
  };
  common: {
    expirationWarning: string;
    minimalScopes: string;
    securityNote: string;
  };
  github: {
    linkText: string;
    note: string;
    scopes: {
      readOrg: string;
      readUser: string;
      repo: string;
    };
    steps: {
      step1: string;
      step2: string;
      step3: string;
      step4: string;
      step5: string;
    };
    title: string;
  };
  gitlab: {
    linkText: string;
    scopes: {
      api: string;
      readApi: string;
      readRepository: string;
    };
    steps: {
      step1: string;
      step2: string;
      step3: string;
      step4: string;
      step5: string;
    };
    title: string;
  };
  title: string;
}

export interface RemediationTranslations {
  agentSession: {
    classifier: string;
    cost: string;
    failureClass: string;
    iterations: string;
    status: {
      budget_exceeded: string;
      failed: string;
      handoff_human: string;
      running: string;
      succeeded: string;
    };
    title: string;
    tokensUsed: string;
    transcript: string;
  };
  audit: {
    action: {
      consolidated: string;
      merged: string;
    };
    allRepos: string;
    columns: {
      action: string;
      autonomy: string;
      completedAt: string;
      pr: string;
      repository: string;
    };
    description: string;
    empty: string;
    exportCsv: string;
    filterRepo: string;
    since: string;
    tableLabel: string;
    title: string;
    until: string;
  };
  autonomyHint: {
    auto_merge: string;
    consolidate: string;
    dry_run: string;
    off: string;
  };
  autonomyLevel: {
    auto_with_approval: string;
    dry_run_only: string;
    fully_autonomous: string;
    suggest_only: string;
  };
  autonomyStop: {
    auto_merge: string;
    consolidate: string;
    dry_run: string;
    off: string;
  };
  ci: {
    columns: {
      check: string;
      status: string;
      type: string;
    };
    empty: string;
    headSha: string;
    logs: string;
    optional: string;
    predictedConflict: string;
    required: string;
    statusCheck: string;
    tableLabel: string;
    title: string;
    tone: {
      green: string;
      red: string;
      yellow: string;
    };
    viewLogs: string;
  };
  conflicts: {
    conflicted: string;
    empty: string;
    skipped: string;
    title: string;
  };
  disposition: {
    closedWithRef: string;
    consolidated: string;
    leftOpen: string;
    skippedConflict: string;
  };
  editor: {
    autonomy: string;
    confirmAutoMerge: {
      confirm: string;
      description: string;
      previewRequired: string;
      title: string;
    };
    createTitle: string;
    description: string;
    editTitle: string;
    enabled: string;
    errors: {
      saveFailed: string;
      scopeIdRequired: string;
    };
    maxPrsPerRun: string;
    minOpenPrs: string;
    noScopes: string;
    save: string;
    saving: string;
    scopeId: string;
    scopeIdPlaceholder: string;
    scopeType: string;
  };
  fleet: {
    airGappedOff: string;
    airGappedOn: string;
    columns: {
      actions: string;
      airGapped: string;
      eligibility: string;
      openPrs: string;
      policyState: string;
      repository: string;
    };
    description: string;
    eligible: string;
    empty: string;
    error: string;
    notEligible: string;
    preview: string;
    tableLabel: string;
    title: string;
  };
  killSwitch: {
    active: string;
    label: string;
    noPolicy: string;
    paused: string;
  };
  modelAccounts: {
    airGapNotice: string;
    apiKey: string;
    apiKeyHint: string;
    apiKeyPlaceholder: string;
    create: string;
    createTitle: string;
    default: string;
    description: string;
    displayName: string;
    displayNamePlaceholder: string;
    egress: {
      external: string;
      local_only: string;
    };
    empty: string;
    endpointUrl: string;
    endpointUrlHint: string;
    endpointUrlPlaceholder: string;
    error: string;
    errors: {
      airGapped: string;
      createFailed: string;
      displayNameRequired: string;
    };
    modelId: string;
    modelIdPlaceholder: string;
    providerKind: string;
    providerKindLabel: {
      claude: string;
      gemini: string;
      ollama: string;
      onnx: string;
    };
    save: string;
    saving: string;
    spend: string;
    spendCap: string;
    title: string;
    validate: string;
    validating: string;
    validationStatus: {
      invalid: string;
      unvalidated: string;
      valid: string;
    };
  };
  modelCatalog: {
    advanced: string;
    codeEdit: string;
    contextWindow: string;
    cost: {
      free: string;
      perToken: string;
    };
    customModelId: string;
    customModelIdHint: string;
    customModelIdPlaceholder: string;
    hardware: {
      community: string;
      diskSize: string;
      filterHint: string;
      filterLabel: string;
      params: string;
      quantization: string;
      ramTier: string;
      tier: {
        '128': string;
        '16': string;
        '32-36': string;
        '64': string;
        all: string;
      };
    };
    loadError: string;
    loading: string;
    model: string;
    modelPlaceholder: string;
    noModels: string;
    pull: {
      notPulled: string;
      pullModel: string;
      pulling: string;
      status: {
        downloading: string;
        error: string;
        queued: string;
        ready: string;
      };
      title: string;
    };
    toolUse: string;
  };
  nav: string;
  playbooks: {
    content: string;
    contentPlaceholder: string;
    create: string;
    description: string;
    duplicate: string;
    empty: string;
    error: string;
    errors: {
      contentRequired: string;
      loadDefaultFailed: string;
      nameRequired: string;
      playbookIdRequired: string;
      previewFailed: string;
      saveFailed: string;
    };
    hints: {
      contextSpec: string;
      heading: string;
      hide: string;
      loop: string;
      outputContract: string;
      providerOverlays: string;
      role: string;
      show: string;
      tasks: string;
      toolsPolicy: string;
    };
    loadDefault: string;
    loadingDefault: string;
    meta: {
      allowedTools: string;
      noTools: string;
      outputContract: string;
      role: string;
    };
    name: string;
    namePlaceholder: string;
    playbookId: string;
    playbookIdPlaceholder: string;
    preview: string;
    previewing: string;
    renderedPrompt: string;
    save: string;
    saving: string;
    scopeId: string;
    scopeIdPlaceholder: string;
    scopeType: string;
    title: string;
    validationError: {
      document: string;
      heading: string;
    };
  };
  policies: {
    create: string;
    description: string;
    disable: string;
    empty: string;
    enable: string;
    statusDisabled: string;
    statusEnabled: string;
    title: string;
  };
  policyState: {
    auto_merge: string;
    auto_with_approval: string;
    disabled: string;
    dry_run: string;
    none: string;
    suggest: string;
  };
  preview: {
    blockedByAirGap: string;
    conflicts: string;
    description: string;
    error: string;
    estimatedDuration: string;
    loading: string;
    noneSelected: string;
    prCount: string;
    seconds: string;
    title: string;
    wouldSelect: string;
  };
  runState: {
    agent_fixing: string;
    awaiting_approval: string;
    cancelled: string;
    completed: string;
    consolidating: string;
    created: string;
    failed: string;
    finalizing: string;
    handoff_human: string;
    merging: string;
    no_op: string;
    selecting: string;
    verifying: string;
  };
  runs: {
    approve: string;
    back: string;
    columns: {
      actions: string;
      pr: string;
      repository: string;
      started: string;
      state: string;
    };
    description: string;
    dispositions: string;
    empty: string;
    error: string;
    noDispositions: string;
    reject: string;
    tableLabel: string;
    timeline: string;
    timelineLabel: string;
    title: string;
    view: string;
  };
  scopeType: {
    org: string;
    repository: string;
    team: string;
    user: string;
  };
  subtitle: string;
  tabs: {
    audit: string;
    fleet: string;
    modelAccounts: string;
    playbooks: string;
    policies: string;
    runs: string;
  };
  title: string;
}

export interface RepositoriesTranslations {
  addFrom: {
    addAll: string;
    close: string;
    empty: string;
    title: string;
  };
  empty: {
    description: string;
    title: string;
  };
  providers: {
    connected: string;
    title: string;
  };
  search: {
    placeholder: string;
  };
  table: {
    actions: string;
    provider: string;
    prs: string;
    repository: string;
    status: string;
  };
  title: string;
  toast: {
    addFailed: string;
    added: string;
    addedDescription: string;
    bulkAddFailed: string;
    bulkAddFailedDescription: string;
    bulkAdded: string;
    bulkAddedDescription: string;
    bulkAddedFailed: string;
    removeFailed: string;
    removed: string;
    removedDescription: string;
  };
}

export interface SettingsTranslations {
  account: {
    avatar: string;
    changePassword: string;
    deleteAccount: string;
    deleteAccountWarning: string;
    displayName: string;
    displayNamePlaceholder: string;
    email: string;
    emailAddress: string;
    emailPlaceholder: string;
    memberSince: string;
    notSet: string;
    profile: string;
    unknown: string;
    yourAccountInfo: string;
  };
  behavior: {
    autoRefresh: string;
    autoRefreshDescription: string;
    defaultView: string;
    defaultViewDescription: string;
    prPerPage: string;
    prPerPageDescription: string;
    refreshInterval: string;
    refreshIntervalDescription: string;
    title: string;
  };
  filtersReset: string;
  filtersResetSuccess: string;
  filtersUpdateFailed: string;
  filtersUpdateSuccess: string;
  filtersUpdated: string;
  general: {
    language: string;
    languageDescription: string;
    theme: string;
    themeDescription: string;
    timezone: string;
    timezoneDescription: string;
  };
  language: {
    description: string;
    title: string;
  };
  notifications: {
    email: string;
    emailDescription: string;
    mentions: string;
    mentionsDescription: string;
    prUpdates: string;
    prUpdatesDescription: string;
    reviews: string;
    reviewsDescription: string;
    title: string;
  };
  prFilters: {
    allowedActors: string;
    allowedActorsDescription: string;
    allowedActorsPlaceholder: string;
    description: string;
    maxAgeDays: string;
    maxAgeDaysDescription: string;
    maxAgeDaysPlaceholder: string;
    skipLabels: string;
    skipLabelsDescription: string;
    skipLabelsPlaceholder: string;
    title: string;
  };
  profileUpdateFailed: string;
  profileUpdateSuccess: string;
  profileUpdated: string;
  providers: {
    bitbucket: string;
    connect: string;
    connected: string;
    disconnect: string;
    github: string;
    gitlab: string;
    notConnected: string;
    token: string;
    tokenDescription: string;
    tokenInstructions: string;
    tokenPlaceholder: string;
  };
  repositories: {
    filter: string;
    filterDescription: string;
    showArchived: string;
    showArchivedDescription: string;
    showForks: string;
    showForksDescription: string;
    visibility: {
      archived: string;
      archivedDescription: string;
      bitbucketNote: string;
      description: string;
      private: string;
      privateDescription: string;
      public: string;
      publicDescription: string;
      title: string;
    };
  };
  reset: string;
  resetConfirm: string;
  save: string;
  saved: string;
  subtitle: string;
  tabs: {
    account: string;
    accounts: string;
    appearance: string;
    behavior: string;
    filters: string;
    general: string;
    notifications: string;
    prFilters: string;
    profile: string;
    providers: string;
    repositories: string;
    repositoryFilters: string;
  };
  title: string;
  updateFailed: string;
}

export interface ValidationTranslations {
  alphanum: string;
  date: string;
  dateRange: string;
  email: string;
  fields: {
    confirmPassword: string;
    displayName: string;
    email: string;
    password: string;
  };
  fileSize: string;
  fileType: string;
  integer: string;
  invalidEmail: string;
  max: string;
  maxLength: string;
  messages: {
    displayNameRequired: string;
    emailRequired: string;
    passwordMinLength: string;
    passwordRequired: string;
  };
  min: string;
  minLength: string;
  negative: string;
  numeric: string;
  passwordMismatch: string;
  passwordsDontMatch: string;
  pattern: string;
  positive: string;
  required: string;
  unique: string;
  url: string;
}

export interface Translations {
  accounts: AccountsTranslations;
  analytics: AnalyticsTranslations;
  behavior: BehaviorTranslations;
  common: CommonTranslations;
  dashboard: DashboardTranslations;
  errors: ErrorsTranslations;
  merge: MergeTranslations;
  notifications: NotificationsTranslations;
  providers: ProvidersTranslations;
  remediation: RemediationTranslations;
  repositories: RepositoriesTranslations;
  settings: SettingsTranslations;
  validation: ValidationTranslations;
}
